In [1]:
import numpy as np
import pandas as pd


In [9]:
df = pd.read_csv('titanic.csv')

In [10]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
df.shape

(891, 12)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [13]:
# EDA
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
df.drop('Cabin', axis=1, inplace=True)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [18]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [19]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [32]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])

In [33]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [34]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [36]:
df.duplicated().sum() # no duplicate are there

np.int64(0)

In [37]:
 df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [38]:
import pandas as pd

def iqr_capping(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    df[col] = df[col].clip(lower, upper)
    return df

num_cols = ['Age', 'Fare', 'SibSp', 'Parch']

for col in num_cols:
    df = iqr_capping(df, col)


In [39]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  Parch  \
count   891.000000  891.000000  891.000000  891.000000  891.000000  891.0   
mean    446.000000    0.383838    2.308642   29.376817    0.426487    0.0   
std     257.353842    0.486592    0.836071   12.062035    0.708246    0.0   
min       1.000000    0.000000    1.000000    2.500000    0.000000    0.0   
25%     223.500000    0.000000    2.000000   22.000000    0.000000    0.0   
50%     446.000000    0.000000    3.000000   29.699118    0.000000    0.0   
75%     668.500000    1.000000    3.000000   35.000000    1.000000    0.0   
max     891.000000    1.000000    3.000000   54.500000    2.500000    0.0   

             Fare  
count  891.000000  
mean    24.046813  
std     20.481625  
min      0.000000  
25%      7.910400  
50%     14.454200  
75%     31.000000  
max     65.634400

In [43]:
# segragate x and y features
X = df.drop(columns={'Survived','PassengerId', 'Name', 'Ticket'}, axis=1)
y=df['Survived']
X.shape, y.shape

((891, 7), (891,))

In [44]:
# train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 7), (179, 7), (712,), (179,))

In [47]:
#train data processing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

In [48]:
ohe = OneHotEncoder()
ohe

OneHotEncoder()

In [55]:
cat = ['Sex', 'Embarked']
ohe = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')

In [56]:
scaler = MinMaxScaler()
scaler

MinMaxScaler()

In [57]:
from sklearn.compose import ColumnTransformer

In [58]:
ct = ColumnTransformer([('ohe',ohe, ['Sex', 'Embarked']),
                       ('scaler',scaler, ['Age', 'Fare', 'SibSp', 'Parch', 'Pclass'])],
                      remainder='passthrough', verbose_feature_names_out=False).set_output(transform='pandas')

In [59]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Sex', 'Embarked']),
                                ('scaler', MinMaxScaler(),
                                 ['Age', 'Fare', 'SibSp', 'Parch', 'Pclass'])],
                  verbose_feature_names_out=False)

In [60]:
X_train_transformed = ct.fit_transform(X_train)
X_train_transformed

Sex_male  Embarked_Q  Embarked_S       Age      Fare  SibSp  Parch  \
692       1.0         0.0         1.0  0.523060  0.860765    0.0    0.0   
481       1.0         0.0         1.0  0.523060  0.000000    0.0    0.0   
527       1.0         0.0         1.0  0.523060  1.000000    0.0    0.0   
855       0.0         0.0         1.0  0.298077  0.142456    0.0    0.0   
801       0.0         0.0         1.0  0.548077  0.399943    0.4    0.0   
..        ...         ...         ...       ...       ...    ...    ...   
359       0.0         1.0         0.0  0.523060  0.120047    0.0    0.0   
258       0.0         0.0         0.0  0.625000  1.000000    0.0    0.0   
736       0.0         0.0         1.0  0.875000  0.523735    0.4    0.0   
462       1.0         0.0         1.0  0.855769  0.586583    0.0    0.0   
507       1.0         0.0         1.0  0.523060  0.404513    0.0    0.0   

     Pclass  
692     1.0  
481     0.5  
527     0.0  
855     1.0  
801     0.5  
..      ...  
359     1.0  
258     0.0  
736     1.0  
462     0.0  
507     0.0  

[712 rows x 8 columns]

In [61]:
from sklearn.neighbors import KNeighborsClassifier

In [62]:
knn = KNeighborsClassifier()
knn

KNeighborsClassifier()

In [63]:
knn.fit(X_train_transformed, y_train)

KNeighborsClassifier()

In [64]:
knn.score(X_train_transformed, y_train)

0.8623595505617978

In [65]:
X_test_transformed = ct.transform(X_test)
X_test_transformed

Sex_male  Embarked_Q  Embarked_S       Age      Fare  SibSp  Parch  \
565       1.0         0.0         1.0  0.413462  0.367947    0.8    0.0   
160       1.0         0.0         1.0  0.798077  0.245298    0.0    0.0   
553       1.0         0.0         0.0  0.375000  0.110079    0.0    0.0   
860       1.0         0.0         1.0  0.740385  0.214953    0.8    0.0   
241       0.0         1.0         0.0  0.523060  0.236157    0.4    0.0   
..        ...         ...         ...       ...       ...    ...    ...   
880       0.0         0.0         1.0  0.432692  0.396134    0.0    0.0   
91        1.0         0.0         1.0  0.336538  0.119666    0.0    0.0   
883       1.0         0.0         1.0  0.490385  0.159977    0.0    0.0   
473       0.0         0.0         0.0  0.394231  0.210129    0.0    0.0   
637       1.0         0.0         1.0  0.548077  0.399943    0.4    0.0   

     Pclass  
565     1.0  
160     1.0  
553     1.0  
860     1.0  
241     1.0  
..      ...  
880     0.5  
91      1.0  
883     0.5  
473     0.5  
637     0.5  

[179 rows x 8 columns]

In [66]:
y_pred = knn.predict(X_test_transformed)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0])

In [67]:
from sklearn.metrics import accuracy_score

In [69]:
accuracy_score(y_test,y_pred)

0.7932960893854749

In [70]:
from sklearn.linear_model import LogisticRegression

In [71]:
lr = LogisticRegression()
lr

LogisticRegression()

In [72]:
lr.fit(X_train_transformed, y_train)

LogisticRegression()

In [73]:
lr.score(X_train_transformed, y_train)

0.7949438202247191

In [74]:
y_pred1 = lr.predict(X_test_transformed)
y_pred1

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0])

In [84]:
accuracy_score(y_test,y_pred1)

0.776536312849162

In [78]:
from sklearn.tree import DecisionTreeClassifier

In [79]:
dt = DecisionTreeClassifier()

In [80]:
dt

DecisionTreeClassifier()

In [81]:
dt.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [82]:
dt.score(X_train_transformed, y_train)

0.9803370786516854

In [83]:
pred2 = dt.predict(X_test_transformed)
pred2

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0])

In [86]:
accuracy_score(y_test,pred2)

0.7988826815642458